---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: create-github-release
spec:
  params:
    - name: githubSecret
      value: ""
    - name: repository
      value: "enriquebelarte/terraform-provider-rhcs-rhtap"
    - name: release_version
      value: 1.0
    - name: content_directory
      value: releases/
  taskRef:
    resolver: "git"
    params:
      - name: url
        value: https://github.com/redhat-appstudio/release-service-bundles.git
      - name: revision
        value: main
      - name: pathInRepo
        value: tasks/create-github-release/create-github-release.yaml
